true
Hide Information=NO_COLOR
Source Code=Dark_Green
Multi CS=NO_COLOR
Locking Scope.Granularity=Orange
AC.Granularity=Orange
Incremental Synchronization=Orange
Conflict Resolution=Orange
Connection Quality=Cyan
remote=Yellow
Centralized=Light_Green
Find Bug Cause=NO_COLOR
Version Data=Yellow
Snapshot Intermediate Versions=Yellow
In the Office – Stable Connection=NO_COLOR
Sequential=Orange
Work_on_digital_artifacts_collabortively=Yellow
Concurrency=Orange
ReadsArtifacts.ACL=Orange
in space/scope.Coarse=Orange
Opperation-based=Orange
Integrated=Light_Green
AccessControlGranularity.Granularity=Orange
ReadsHistory.None=Orange
Locking Scope.Coarse=Orange
VersionInterval.Immediately=Orange
Snapshot Latest Version=Yellow
Writes.Capability-based=Orange
Two=NO_COLOR
LWW=Orange
Type_of_Artifact_find_better_Name=Light_Green
SpaceGranularity.Fine=Orange
Line=Orange
Usable With Good Connection=Cyan
Artifacts=Dark_Green
Plain Text=Dark_Green
Time of Change=Orange
Context Information=Yellow
Delete Information=NO_COLOR
Domain-specific=Orange
Writes.None=Orange
Common Ancestor Merge=Orange
User Presence=Orange
ReadsHistory.Access Control=Orange
ReadsArtifacts.Capability-based=Orange
Writes.Authenticated=Orange
IP Protection=NO_COLOR
VersionInterval.Interval=Orange
Timestamp=Yellow
in Artifact Versions=Orange
Usable With No Connection=Cyan
2-way Diff=Orange
Versioning Quality=Cyan
ReadsHistory.Authentication=Orange
Standalone=Light_Green
Writes.Anonymous=Orange
Editor Integration=Light_Green
Files=Dark_Green
Operating Environment=Light_Green
ReadsArtifacts.Authenticated=Orange
Branching=Light_Green
Movements=Orange
Usage Context=Dark_Green
Disturbance Free=Cyan
Querying=NO_COLOR
Offline Read=Orange
Communication Protocol=Light_Green
Reads.Access Control=Orange
ReadsHistory.AuthenticationAccessControl=Orange
Tooling=Dark_Green
Selected Elements=Orange
Reads.ACL=Orange
Layout=Orange
Avoid Inconsistencies=Orange
Fast Restore Any Version=Cyan
Writes=Orange
Append-only Merge=Orange
Location of Data=Yellow
Implicit=Orange
Supported CSs=NO_COLOR
Collaboration Mode=Orange
Syntax=Orange
Integrate Conflicts in Model=Orange
Other=Dark_Green
Read meta-info=Orange
Compliance=NO_COLOR
AuthenticationControlRead=Orange
Writes.Access Control=Orange
Change Scope.Granularity=Orange
ReadsHistory.Capability-based=Orange
ReadsHistory.Anonymous=Orange
Explicit=Orange
Low Memory Footprint=Cyan
Platform =Yellow
Graphical User Interface=Dark_Green
State-based CRDT=Yellow
Visualization of Differences=Orange
In the Office - Stable Connection=Dark_Green
What_kind_of_Artifacts_questionmark=Light_Green
in space/scope.Fine=Orange
Reads.None=Orange
Understand Model Evolution=NO_COLOR
ReadsArtifacts.Authentication=Orange
Off the Map – Offline=NO_COLOR
ReadsArtifacts.None=Orange
ReadsArtifacts.Access Control=Orange
Diffing Algorithms=Yellow
Other Information=Yellow
Change Scope.Coarse=Orange
Integrated in Artifact Editor=Dark_Green
Authenticated Writes=Orange
PullInterval.Manually=Orange
Reads.Authentication=Orange
Meta-data=Orange
Diff Visualization=Light_Green
Low Disk Space Usage=Cyan
ReadsArtifacts.AuthenticationAccessControl=Orange
full=Yellow
Writes.Authentication=Orange
Context of Evolution=NO_COLOR
PushInterval.Immediately=Orange
Merging=Orange
Fast Restore Latest Version=Cyan
Peer-2-Peer=Light_Green
Design Decision=Yellow
Meta Data=Yellow
Branching Support=Orange
Client-Server=Light_Green
Centralized Access Control=Yellow
Quality Collaboration=NO_COLOR
Size of Model=Orange
Obfuscate Information=NO_COLOR
Seamless Transition=Orange
Anonymous Writes=Orange
Derive deltas=Orange
Record Evolution=NO_COLOR
Operation-based CRDT=Yellow
Linear=Yellow
Publish Work=NO_COLOR
Capabilities=Orange
PushInterval.Time-triggered=Orange
Are_Communication_Capabilities_covered_questionmark=Red
Get Statistics on Evolution=NO_COLOR
Collaboration Quality=Cyan
Location=Dark_Green
3-way Diff=Orange
ReadsHistory.Authenticated=Orange
Reads.Capability-based=Orange
Asynchronous=Orange
Platform=Dark_Green
Layout manually=NO_COLOR
Deal with Evolution=NO_COLOR
Concurrent=Orange
Heuristics=Orange
Manual=Orange
Users=Dark_Green
Encryption=Yellow
Record Meta-data=Orange
Constructive=Orange
Incrementing Integers=Yellow
Network=Light_Green
Restrict=NO_COLOR
Level of AS=Light_Green
Calculation=Orange
GUIDs=Yellow
GUI=Light_Green
Offline Access=Orange
Access Control=Yellow
in space/scope.Granularity=Orange
History of Operations=Orange
Operations=Yellow
PullInterval.Time-triggered=Orange
Pessimistic Locking=Orange
AccessControlGranularity.Coarse=Orange
Usable With Poor Connection=Cyan
Primitive History Entries=Yellow
Undo=NO_COLOR
On the Road - Unstable Connection=Dark_Green
Persist Abstract Syntax=Orange
PullInterval.Immediately=Orange
Concatenation=Orange
Destructive=Orange
Version IDs=Yellow
PullInterval.Interval=Orange
Artisan Layout=Orange
Models=Dark_Green
partial=Yellow
Composite / Transactions=Orange
Anonymous Reads=Orange
Deterministic Layout=Orange
Writes.AuthenticationAccessControl=Orange
Communication with Collaborators=Cyan
Unguessable ID=Yellow
Persist Concrete Syntax=Orange
History Structure=Yellow
Direction=Orange
Directed Acyclic Graph=Yellow
local=Yellow
Merge Visualization=Light_Green
History Persistence=Orange
Locking Scope.Fine=Orange
AC.Fine=Orange
AC.Coarse=Orange
Reads.Anonymous=Orange
Load Previous Versions=NO_COLOR
Operations Data=Yellow
Table=Dark_Green
AccessControlGranularity.Fine=Orange
Diff-based=Orange
Edit Operations=Yellow
Modify=NO_COLOR
Multi=Dark_Green
Based on Operations=Orange
SpaceGranularity.Granularity=Orange
Edit Operation Information=Light_Green
Supported Collaborators=NO_COLOR
VersionInterval.Time-triggered=Orange
Single CS=NO_COLOR
PushInterval.Interval=Orange
In Real-time=Cyan
Restrict Append and Write Access=NO_COLOR
Authentication=Orange
Problem Space=NO_COLOR
Query History=Orange
Receive=Orange
Real-Time Change Propagation=Light_Green
None=Yellow
Complex Strategy=Orange
Snapshots of State=Yellow
Awareness of Collaborators=Cyan
Versioning Expertise=Dark_Green
ReadsArtifacts.Anonymous=Orange
Visualization of Conflicts=Orange
Bi-directional Synchronization CS/AS=Orange
Content Addressed=Yellow
Command Line Interface=Dark_Green
On the Road – Unstable Connection=NO_COLOR
Synchronous=Orange
Random=Orange
Change Scope.Fine=Orange
Ability and Desire to Setup Own Server=Dark_Green
Conflict Detection Algorithm=Yellow
Restrict Read Access=NO_COLOR
Compare Two Versions=Orange
FWW=Orange
Decentralized=Light_Green
State Data=Yellow
SpaceGranularity.Coarse=Orange
Conflict Detection=Yellow
Reads.AuthenticationAccessControl=Orange
Authenticated Reads=Orange
Off the Map - Offline=Dark_Green
Offline Write=Orange
Goals=NO_COLOR
File=Orange
User=Yellow
Snapshots for Performance=Yellow
Ghost Cursor=Orange
Network Topology=Light_Green
Metamodel of Deltas=Orange
On the Road - Unstable Connection=Dark_Green
Layout Continuity=Cyan
Operation-based=Orange
Persist Abstract Representation=Orange
Level of CS=Light_Green
Hundreds=NO_COLOR
No Accidental Loss of Information=Cyan
Publish=Orange
Locking=Yellow
On the Road -�Unstable Connection=Dark_Green
Retroactive Modification=Orange
Postponed_commit=Orange
Quality Requirements=Cyan
Persistent=Orange
Decentralized Access Control=Yellow
Data=Yellow
Insert in List=Orange
Specific=Yellow
Reads.Authenticated=Orange
VersionInterval.Manually=Orange
Writes.ACL=Orange
ReadsHistory.ACL=Orange
PushInterval.Manually=Orange
Independent=Yellow
Temporary=Orange
File System=Orange
Single=Dark_Green
Operation-based Diff=Orange
Insert in list=Red
Granularity of Changes=Orange
History of State=Orange
Up to Ten=NO_COLOR
